a=set()
a.add(1)
a.add(2)
a.add(3)
a.add(4)
a.add(5)
a.add(6)
print("Conjunto a",a)
b=set()
b.add(3)
b.add(4)
b.add(5)
b.add(6)
b.add(8)
b.add(10)
print("Conjunto b",b)
c=set()
c.add(3)
c.add(5)
c.add(9)
print("conjunto c",c)
b.discard(8)
print("Conjunto b",b)
d=a.copy()
print("Conjunto d",d)
c.clear()
print("conjunto c",c)
c=b.copy()
print("conjunto c",c)
print(c.isdisjoint(b))
print(c.isdisjoint(a))
e=set()
e.add(3)
e.add(4)
print(e.issubset(b))
print(e.issubset(a))
print(e.issubset(d))
print(b.issubset(d))
print(b.issuperset(a))
print(e.issuperset(a))
f=c.union(b)
print("Conjunto f", f)
a.update(b)
print("Conjunto A", a)
print(a.difference(b))
a.difference_update(b)
print("Conjunto A", a)
print(c.intersection(d))
c.intersection_update(d)
print("Conjunto A", a)
print("Conjunto B", b)
print("Conjunto C", c)
print("Conjunto D", d)
print("Conjunto E", e)
print("Conjunto F", f)
print(c.symmetric_difference(d))